$ANSIBLE_VAULT;1.2;AES256;dev
34363037626661663237653436383930366539306564383838356566666331326330353536316531
6265646131393834336632373061636163383937323235320a313066666339393963343239353734
32303437643638333333613965343630346630623438303962333533613965663164373430613464
3166633837653932300a623930303730613966376237633139343631323030313134323063363739
62626430646462633666303061316636373438636635383335613637663462636230
